repos:
- repo: https://github.com/mpalmer/action-validator
  rev: v0.8.0
  hooks:
  - id: action-validator
    exclude: action.yml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    exclude: action.yml
    args: [--unsafe] 
