# Example workflow using the yamllint composite action
# Save as .github/workflows/yamllint.yml

name: YAML Lint

on:
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - '**/*.yml'
  #     - '**/*.yaml'
  # push:
  #   paths:
  #     - '**/*.yml'
  #     - '**/*.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Run yamllint composite action
        uses: ./.github/actions/composite/yamllint
        with:
          yamllint_config_data: ''  # Optionally set yamllint config data
          yamllint_config_file: ''  # Optionally set to .yamllint or another config file
          yamllint_files_or_dirs: '**/*.yml **/*.yaml'  # Optionally override file globs
